### ISSUE TITLE
Tag new version

### ISSUE THREAD

**Issue by nazavode** [alalazo/modern_wheel#14]
Just wondering if the latest version could be tagged, @zzotta is the guy to be blamed as usual.

**Comment by alalazo** [comment]
Sanctum per saecula nomen legatus

**Comment by alalazo** [comment]
@nazavode @zzotta Feel free to close the issue if release `1.2` is fine with you

**Comment by nazavode** [comment]
Большое спасибо!

**Comment by nazavode** [comment]
Большое спасибо!
